# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'MyFistGithubProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage','3.7.3'
pod 'MLeaksFinder' ,:configurations => ['Debug']

  target 'MyFistGithubProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFistGithubProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
